const fs = require('fs');
const path = require('path');

const markdownPath = path.resolve(__dirname, '..', 'source_per_food.md');

const badFoods = [
  // Nhóm Đồ uống ngọt
  { id: "tra_sua", name: "Trà sữa trân châu", category: "Đồ uống công nghiệp", nutrition: "Chứa rất nhiều đường tinh luyện, kem béo thực vật (trans fat) và tinh bột từ trân châu. 1 ly có thể chứa 50g đường và 400-600 kcal.", benefits: ["Cung cấp năng lượng tức thời nhưng giảm nhanh."], bad_combinations: [], consumption_tips: "Uống nhiều gây nổi mụn, mệt mỏi, khó tập trung học tập, dễ tăng cân và kháng insulin. Nên giới hạn 1-2 lần/tháng và chọn mức 0-30% đường." },
  { id: "nuoc_ngot", name: "Nước ngọt có gas", category: "Đồ uống công nghiệp", nutrition: "Chứa lượng đường khổng lồ (khoảng 39g/lon), phẩm màu và axit photphoric làm mòn men răng.", benefits: ["Giải khát tạm thời."], bad_combinations: [], consumption_tips: "Gây nghiện đường, làm xốp xương ở tuổi dậy thì, dẫn đến béo phì. Hãy đổi sang uống nước lọc hoặc nước ép trái cây không đường." },
  { id: "nuoc_tang_luc", name: "Nước tăng lực", category: "Đồ uống công nghiệp", nutrition: "Nhiều đường, caffeine hàm lượng cao và các chất kích thích nhân tạo.", benefits: ["Giúp tỉnh táo tạm thời."], bad_combinations: [], consumption_tips: "Làm nhịp tim nhanh, hồi hộp, gây mất ngủ và suy giảm trí nhớ nếu dùng lâu dài. Trẻ vị thành niên nên tránh xa." },
  { id: "siro_tra_chanh", name: "Trà chanh đóng chai", category: "Đồ uống công nghiệp", nutrition: "Hầu như không có trà tự nhiên, chủ yếu là hương liệu và đường hóa học.", benefits: ["Hương vị đánh lừa vị giác dễ chịu."], bad_combinations: [], consumption_tips: "Cung cấp 'calo rỗng' gây tích mỡ bụng. Nên tự pha trà chanh từ trà mạn và chanh tươi với ít mật ong." },
  { id: "sua_dac", name: "Sữa đặc có đường", category: "Sản phẩm công nghiệp", nutrition: "Hơn 45% là đường mía tinh luyện, chất béo động vật cao.", benefits: ["Pha cà phê hoặc chấm bánh mì ngon miệng."], bad_combinations: [], consumption_tips: "Ăn quá nhiều sẽ dư thừa đường nghiêm trọng. Không nên pha làm đồ uống chính thay sữa tươi." },
  { id: "nuoc_ep_dong_hop", name: "Nước ép đóng chai", category: "Đồ uống công nghiệp", nutrition: "Mất hết chất xơ, vitamin bị phá hủy qua xử lý nhiệt, thường chứa thêm siro bắp (HFCS).", benefits: ["Tiện lợi hơn việc vắt trái cây tươi."], bad_combinations: [], consumption_tips: "Uống vào sẽ nạp ngay một lượng đường fructose vào gan, dễ gây gan nhiễm mỡ. Hãy ăn trái cây nguyên múi." },
  { id: "nuoc_khoang_Ngot", name: "Nước khoáng vị trái cây", category: "Đồ uống công nghiệp", nutrition: "Đánh lừa người dùng là nước khoáng nhưng thực chất chứa đường hóa học và hương liệu.", benefits: ["Có vị ngọt nhẹ."], bad_combinations: [], consumption_tips: "Thực chất là nước ngọt pha loãng. Đường hóa học gây rối loạn hệ vi sinh đường ruột." },

  // Nhóm Fast food & Đồ chiên ngập dầu
  { id: "ga_ran", name: "Gà rán công nghiệp", category: "Thức ăn nhanh", nutrition: "Nhiều dầu mỡ, lớp bột chiên hút nhiều dầu (trans fat và bão hòa), giàu calo nhưng nghèo vi chất.", benefits: ["Rất hấp dẫn, ngon miệng và tiện lợi."], bad_combinations: [], consumption_tips: "Dầu chiên đi chiên lại sinh ra chất độc. Gây nóng trong, nổi mụn, béo phì. Cố gắng bóc bỏ lớp bột chiên nếu ăn." },
  { id: "khoai_tay_chien", name: "Khoai tây chiên", category: "Thức ăn nhanh", nutrition: "Chứa nhiều tinh bột tiêu hóa nhanh, dầu mỡ và lượng muối natri cao. Nhiệt độ cao sinh ra acrylamide.", benefits: ["Ăn vặt giòn ngon."], bad_combinations: [], consumption_tips: "Rất dễ gây nghiện. Dư thừa muối làm hại thận và tăng huyết áp sớm. Gây viêm da và mụn trứng cá." },
  { id: "hamburger", name: "Hamburger", category: "Thức ăn nhanh", nutrition: "Chứa thịt chế biến, phô mai nhiều béo, vỏ bánh mì trắng (carbohydrate tinh chế).", benefits: ["Nhanh chóng no bụng."], bad_combinations: [], consumption_tips: "Thiếu chất xơ nghiêm trọng, gây táo bón và chậm tiêu. Nếu ăn nên gọi thêm nhiều rau xanh và không dùng sốt béo." },
  { id: "pizza", name: "Pizza công nghiệp", category: "Thức ăn nhanh", nutrition: "Dư thừa tinh bột tinh chế, nhiều chất béo bão hòa từ phô mai và thịt xông khói.", benefits: ["Món ăn tiệc tùng hấp dẫn."], bad_combinations: [], consumption_tips: "Lượng calo rất khủng (khoảng 300 kcal/miếng). Hạn chế ăn đế dày và viền phô mai, ưu tiên pizza nhiều rau củ." },
  { id: "ca_vien_chien", name: "Xiên bẩn (Cá/Bò viên)", category: "Đồ chiên đường phố", nutrition: "Chủ yếu là bột, phụ gia tạo dai, hàn the và chiên trong dầu không đảm bảo.", benefits: ["Giá rẻ, hương vị tẩm ướp kích thích."], bad_combinations: [], consumption_tips: "Dầu mỡ đen, tái sử dụng nhiều lần sinh ra chất gây ung thư. Thành phần thịt không rõ ràng gây hại hệ tiêu hóa." },
  { id: "pho_mai_que", name: "Phô mai que chiên xù", category: "Đồ chiên đường phố", nutrition: "Nhân phô mai nhân tạo bọc trong lớp vỏ bột hút đẫm dầu chiên.", benefits: ["Kéo sợi phô mai dai ngon thú vị."], bad_combinations: [], consumption_tips: "Rất nặng bụng. Gây quá tải gan nếu ăn nhiều do dầu mỡ tái chế kém chất lượng." },
  { id: "nem_ran", name: "Nem chua rán", category: "Đồ chiên đường phố", nutrition: "Thịt lợn bì trộn thính nhưng đem chiên ngập trong chảo dầu vỉa hè.", benefits: ["Mùi vị cuốn hút, dễ ăn vặt."], bad_combinations: [], consumption_tips: "Gây mụn nhọt, viêm da và béo bụng do trans-fat." },

  // Nhóm Thịt chế biến (Processed Meat)
  { id: "xuc_xich", name: "Xúc xích công nghiệp", category: "Thịt chế biến", nutrition: "Nhiều chất bảo quản (Nitrat, Nitrit), muối natri, bột và chất béo vụn.", benefits: ["Dễ ăn, tiện lợi, hợp khẩu vị trẻ em."], bad_combinations: [], consumption_tips: "WHO xếp thịt chế biến vào nhóm gây ung thư. Ăn nhiều gây rối loạn tiêu hóa, béo phì. Nên thay bằng thịt lợn tươi." },
  { id: "thit_xong_khoi", name: "Thịt xông khói (Bacon)", category: "Thịt chế biến", nutrition: "Rất nhiều muối và mỡ động vật. Quá trình xông khói sinh ra hợp chất gây hại.", benefits: ["Thơm ngon đặc trưng."], bad_combinations: [], consumption_tips: "Cực kỳ hại cho hệ tim mạch và làm tăng nguy cơ bệnh đường ruột. Tuyệt đối không nên ăn hàng ngày." },
  { id: "dam_bong", name: "Dăm bông (Jambon)", category: "Thịt chế biến", nutrition: "Thịt muối chứa dư lượng nitrat làm tăng gánh nặng cho gan thận.", benefits: ["Tiện lợi cho bữa sáng."], bad_combinations: [], consumption_tips: "Nên thay thế bằng thịt gà luộc hoặc trứng luộc tươi cho bữa sáng." },
  { id: "lap_xuong", name: "Lạp xưởng", category: "Thịt chế biến", nutrition: "Hơn 50% là mỡ động vật, nhiều đường và chất bảo quản.", benefits: ["Đưa cơm, mùi vị đặc trưng."], bad_combinations: [], consumption_tips: "Là món ăn cực nghèo vi chất nhưng lại dư thừa calo xấu. Dễ gây đầy bụng, ợ hơi." },
  { id: "pate_dong_hop", name: "Pate đóng hộp", category: "Thịt chế biến", nutrition: "Chứa nhiều mỡ lợn, gan có thể tích tụ độc tố nếu không rõ nguồn gốc, chất bảo quản.", benefits: ["Nhanh gọn lẹ."], bad_combinations: [], consumption_tips: "Nếu ăn nên chọn pate tự làm tươi. Hàng đóng hộp chứa quá nhiều natri không tốt cho học sinh." },
  { id: "thit_hop", name: "Thịt hộp (Spam)", category: "Thịt chế biến", nutrition: "Ngập trong muối natri và mỡ bão hòa để bảo quản lâu năm.", benefits: ["Ăn kèm với mì tôm rất tiện."], bad_combinations: [], consumption_tips: "Gây tích nước cơ thể do thừa muối, tăng áp lực lên hệ thống mạch máu." },

  // Nhóm Snack & Ăn vặt công nghiệp
  { id: "mi_tom", name: "Mì ăn liền (Mì tôm)", category: "Siêu chế biến", nutrition: "Sợi mì chiên ngập dầu (nhiều trans fat), không có vitamin, chất xơ. Gói gia vị chứa rất nhiều muối và bột ngọt.", benefits: ["Cứu đói cấp tốc, giá rẻ."], bad_combinations: [], consumption_tips: "Gây nóng trong, nổi mụn bọc, khó tiêu hóa. Mất tới nhiều ngày để đào thải lớp sáp bảo quản. Chỉ nên ăn khi thật cần thiết." },
  { id: "bim_bim", name: "Bim bim (Snack)", category: "Ăn vặt công nghiệp", nutrition: "Thành phần chính là bột, hương liệu nhân tạo, đường, muối và dầu chiên.", benefits: ["Nhai giòn vui miệng."], bad_combinations: [], consumption_tips: "Ăn bim bim sẽ làm mất cảm giác ngon miệng trong bữa chính, gây thiếu hụt vi chất dẫn đến thấp còi nhưng vẫn béo bụng." },
  { id: "kem_cong_nghiep", name: "Kem công nghiệp", category: "Đồ ngọt tinh chế", nutrition: "Rất nhiều đường trắng và hương liệu, sữa bột nhân tạo, chất béo bão hòa.", benefits: ["Giải nhiệt mùa hè cực đã."], bad_combinations: [], consumption_tips: "Làm tổn thương màng nhầy cổ họng nếu ăn lạnh, lượng đường lớn làm da nhạy cảm dễ viêm mụn." },
  { id: "banh_ngot", name: "Bánh ngọt đóng gói", category: "Đồ ngọt tinh chế", nutrition: "Làm từ bột mì tinh chế (mất hết chất xơ), bơ nhân tạo (margarine) và đường.", benefits: ["Thơm mềm dễ ăn."], bad_combinations: [], consumption_tips: "Tăng đường huyết rất nhanh khiến sau khi ăn 1-2 tiếng cơ thể sẽ mệt mỏi, buồn ngủ (sugar crash), ảnh hưởng học tập." },
  { id: "keo_mut", name: "Kẹo mút / Kẹo dẻo", category: "Đồ ngọt nhân tạo", nutrition: "100% đường tinh luyện, chất tạo màu và hương liệu hóa học.", benefits: ["Màu sắc bắt mắt."], bad_combinations: [], consumption_tips: "Kẻ thù số một của men răng, gây sâu răng nhanh chóng. Đường nhân tạo làm giảm khả năng tập trung (tăng động giảm chú ý)." },
  { id: "socola_cong_nghiep", name: "Socola sữa công nghiệp", category: "Đồ ngọt tinh chế", nutrition: "Chứa rất ít ca cao (thường dưới 20%), còn lại là đường và chất béo thực vật rẻ tiền.", benefits: ["Ngọt ngào, nạp năng lượng nhanh."], bad_combinations: [], consumption_tips: "Nên chọn Socola đen (từ 70% ca cao trở lên). Socola sữa rẻ tiền chỉ mang lại đường và béo." },

  // Nhóm thực phẩm tiềm ẩn nguy cơ khác
  { id: "trai_cay_say_tam_duong", name: "Trái cây sấy tẩm đường", category: "Ăn vặt công nghiệp", nutrition: "Trái cây sấy mất đi vitamin C, lại được tẩm thêm rất nhiều đường để bảo quản.", benefits: ["Bảo quản được lâu, vị ngọt đậm."], bad_combinations: [], consumption_tips: "Nhìn có vẻ 'healthy' nhưng thực chất lượng đường cao gấp 5-10 lần trái cây tươi. Nên ăn trái cây tươi." },
  { id: "bo_thuc_vat", name: "Bơ thực vật (Margarine)", category: "Chất béo công nghiệp", nutrition: "Được làm từ dầu thực vật hydro hóa (chứa nhiều Trans fat nhất).", benefits: ["Rẻ, bảo quản nhiệt độ phòng, dễ nướng bánh."], bad_combinations: [], consumption_tips: "Trans fat là loại chất béo độc hại nhất gây tắc nghẽn mạch máu, mỡ máu ở người trẻ tuổi. Tránh xa tuyệt đối." },
  { id: "ngu_coc_ngot", name: "Ngũ cốc ăn sáng tẩm màu", category: "Đồ ngọt tinh chế", nutrition: "Được quảng cáo là tốt nhưng chứa hàm lượng đường cực kỳ cao và phẩm màu.", benefits: ["Giòn, trẻ em rất thích khi đổ vào sữa."], bad_combinations: [], consumption_tips: "Khiến buổi sáng bắt đầu bằng một 'cú sốc' đường huyết. Nên chọn Yến mạch nguyên hạt ít đường." },
  { id: "boba", name: "Trân châu đen", category: "Đồ ngọt tinh chế", nutrition: "Làm từ bột sắn dây/khoai mì đun trong nước đường đen, hoàn toàn không có vitamin.", benefits: ["Nhai dai dẻo xả stress."], bad_combinations: [], consumption_tips: "Rất dễ gây nghẹn. Ăn nhiều gây đầy bụng, không tiêu và dư thừa tinh bột xấu, dẫn đến mỡ thừa bắp tay, bắp đùi." }
];

function appendToMarkdown() {
  let content = fs.readFileSync(markdownPath, 'utf8');
  
  const newSection = `\n\n### 🔴 Đợt 11: Thực phẩm Gây hại (Cần hạn chế)\n\n\`\`\`json\n${JSON.stringify(badFoods, null, 2)}\n\`\`\`\n`;
  
  fs.appendFileSync(markdownPath, newSection, 'utf8');
  console.log("✅ Đã thêm 30 thực phẩm gây hại vào source_per_food.md");
}

appendToMarkdown();
